server:
  port: 8761
  response-cache-update-interval-ms: 500
eureka:
  server:
    renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false